### ISSUE TITLE
mi35x-qwen3-235b-mxfp4 failed since v0.1.12.post1

### ISSUE THREAD

**Issue by bingxche** [ROCm/aiter#2857]
## Summary

Since aiter `v0.1.12.post1`, the `nightly-8-gpu-mi35x-qwen3-235b-mxfp4` job in [sgl-project/sglang](https://github.com/sgl-project/sglang) nightly CI has been crashing consistently during CUDA graph capture on AMD MI35x GPUs. The server process aborts (`SIGABRT`, exit code -6) during initialization — no test ever runs.

The crash was introduced by the IPC mechanism rewrite in v0.1.12.post1 (`IPCBufferPool` / `_gather_ipc_meta` refactor). The same job passed consistently on v0.1.11.post1.

## Failure History (11 consecutive nightly failures over 11 days)

| Date | Result | Job Link |
|------|--------|----------|
| 04-09 | **PASS** (aiter v0.1.11.post1) | [run 24204946865](https://github.com/sgl-project/sglang/actions/runs/24204946865/job/70658215549) |
| 04-11 | **FAIL** (aiter v0.1.12.post1) | [job 70828372535](https://github.com/sgl-project/sglang/actions/runs/24256232445/job/70828372535) |
| 04-12 | **FAIL** | [job 70945486323](https://github.com/sgl-project/sglang/actions/runs/24288005840/job/70945486323) |
| 04-12 | **FAIL** | [job 70984670927](https://github.com/sgl-project/sglang/actions/runs/24312584276/job/70984670927) |
| 04-14 | **FAIL** | [job 71130716260](https://github.com/sgl-project/sglang/actions/runs/24358226838/job/71130716260) |
| 04-14 | **FAIL** | [job 71319843279](https://github.com/sgl-project/sglang/actions/runs/24414482963/job/71319843279) |
| 04-15 | **FAIL** | [job 71506238357](https://github.com/sgl-project/sglang/actions/runs/24469668959/job/71506238357) |
| 04-17 | **FAIL** | [job 71694962058](https://github.com/sgl-project/sglang/actions/runs/24525632849/job/71694962058) |
| 04-17 | **FAIL** | [job 71871294717](https://github.com/sgl-project/sglang/actions/runs/24578887969/job/71871294717) |
| 04-18 | **FAIL** | [job 71963419934](https://github.com/sgl-project/sglang/actions/runs/24610307143/job/71963419934) |
| 04-19 | **FAIL** | [job 72029329928](https://github.com/sgl-project/sglang/actions/runs/24635222311/job/72029329928) |
| 04-21 | **FAIL** | [job 72454269669](https://github.com/sgl-project/sglang/actions/runs/24737667212/job/72454269669) |

The aiter version bump was done in sglang commit [2130279](https://github.com/sgl-project/sglang/commit/213027951a31342400aa6f489691ca0626bf76c7) (`[AMD] Upgrade Aiter (#22264)`, 2026-04-11), changing `AITER_COMMIT_DEFAULT` from `v0.1.11.post1` to `v0.1.12.post1`.

## Reproduce Command

```
sglang serve --model-path amd/Qwen3-235B-A22B-Instruct-2507-mxfp4 \
  --tp 4 --ep 2 --trust-remote-code --attention-backend aiter \
  --device cuda --host 127.0.0.1 --port 11000
```

Environment: 8× AMD MI35x, ROCm, `SGLANG_USE_AITER=1`.

## Error Message

```
[rank3]:[E421 22:56:09 ProcessGroupNCCL.cpp:2055] [PG ID 5 PG GUID 23 Rank 1]
Process group watchdog thread terminated with exception:
HIP error: operation not permitted when stream is capturing
Search for `hipErrorStreamCaptureUnsupported'

[rank3]:[E421 22:56:09 ProcessGroupNCCL.cpp:2055] [PG ID 6 PG GUID 27 Rank 1]
Process group watchdog thread terminated with exception:
HIP error: operation not permitted on an event last recorded in a capturing stream
Search for `hipErrorCapturedEvent'
```

## Crash Call Stack

```
custom_all_reduce.py:403   CustomAllreduce.capture().__exit__  [finally block]
  → custom_all_reduce.py:203   IPCBufferPool.flush_graph_buffers()
    → custom_all_reduce.py:236   IPCBufferPool._gather_ipc_meta()   # pickle.dumps(shard_data)

model_runner.py:2610  init_device_graphs
  → cuda_graph_runner.py:665   CudaGraphRunner.__init__
    → cuda_graph_runner.py:823   CudaGraphRunner.capture
      → parallel_state.py:1533   graph_capture()  [context manager exit]
        → parallel_state.py:505   GroupCoordinator.graph_capture()  [context manager exit]
          → custom_all_reduce.py:403   capture().__exit__   ← crash here
```

### [Confidence: HIGH ~90%] The IPC rewrite in v0.1.12.post1 changed `_gather_ipc_meta` behavior during graph capture exit

In **v0.1.11.post1**, `capture().__exit__` called `register_graph_buffers()` → `_gather_ipc_meta()`, which used:
```python
dist.broadcast_object_list(all_data[i], src=rank, group=self.group, device="cpu")
```
This goes through the **gloo CPU backend** — no GPU stream interaction, safe during/after CUDA graph capture.

In **v0.1.12.post1**, `capture().__exit__` calls `flush_graph_buffers()` → `_gather_ipc_meta()`, which now uses:
```python
self._store.set(f"{prefix}/r{self._rank}", pickle.dumps(shard_data))
```
where `shard_data` is `(handle, offset)` containing tensors created by `torch.empty(count * handle_sz, dtype=torch.uint8)` and `torch.empty(count, dtype=torch.int64)`. The `pickle.dumps` on these tensors triggers implicit device synchronization or memory operations. Meanwhile, the NCCL `ProcessGroup` watchdog thread is checking events on streams that are still in capture mode, which triggers `hipErrorStreamCaptureUnsupported` / `hipErrorCapturedEvent`.

### [Confidence: MEDIUM ~60%] The buffer allocation changes may also contribute

v0.1.12.post1 changed `max_size` from `128MB` to `1GB` and restructured buffer management (removed `output_buffer`, introduced `IPCBufferPool`). The larger allocation may change memory layout and affect which GPU memory regions are involved during graph capture, potentially creating more IPC registration work in `flush_graph_buffers`.

### [Confidence: MEDIUM ~50%] The issue may be specific to multi-PG configurations (TP=4, EP=2)

Other MXFP4 models (DeepSeek-R1-MXFP4, GLM5-MXFP4) on the same MI35x hardware pass with v0.1.12.post1. The Qwen3-235B test uses `--tp 4 --ep 2`, which creates multiple process groups that all enter `graph_capture()` simultaneously (via `parallel_state.py:1533-1541`). Each PG's `ca_comm.capture()` calls `flush_graph_buffers` on exit, and the interleaved exits may cause the NCCL watchdog on one PG to observe the still-capturing stream of another.

## Suggested Fix Direction

1. Ensure tensors passed to `pickle.dumps` in `_gather_ipc_meta` are explicitly on CPU (e.g., `torch.empty(..., device='cpu')`) — though the current code may already do this, the serialization itself may still trigger device sync.
2. Ensure the CUDA graph capture stream has fully ended before `flush_graph_buffers` runs — e.g., by calling `stream.synchronize()` or `torch.cuda.current_stream().synchronize()` before the IPC exchange.
3. Consider whether `flush_graph_buffers` can be deferred to run **after** all `graph_capture()` context managers have exited, rather than in each PG's `capture().__exit__`.

**Comment by TennyWang1223** [comment]
I think the three hypotheses are off. Here's what I found after diffing both versions.

  ## On the three hypotheses

  **Hyp.1 (pickle triggers device sync):** The two tensors are CPU tensors (no `device=`, defaults to CPU). Pickling CPU tensors doesn't touch any GPU stream. On the C++ side, `get_graph_buffer_ipc_meta` only does host-side `std::memcpy` from a `std::vector<uint8_t>` —
  no D2H copy. IPC handles are pure host bytes from `hipIpcGetMemHandle`. I diffed the C++ `get_graph_buffer_ipc_meta` and `register_graph_buffers` between v0.1.11.post1 and v0.1.12.post1 — functionally identical, only the Python↔C++ ABI shape changed.

  **Hyp.2 (buffer allocation changes):** `max_size` and `IPCBufferPool` don't intersect the graph-capture path. Those buffers are pre-registered at init and live in the `input_buffer` / `output_buffers_` maps — they never enter `graph_unreg_*_buffers_`.

  **Hyp.3 (multi-PG specific):** Amplifier, not driver. Any model that captures enough graphs would hit it.

  ## More likely cause

  C++ commit [`5759ee2`](https://github.com/ROCm/aiter/commit/5759ee2) ("fix(car): graph capture err"), which landed in v0.1.12.post1. It changed `get_buffer_RD` / `get_output_buffer_RD` to **unconditionally** push to `graph_unreg_*_buffers_` during capture, bypassing
  the cache:

  ```cpp
  // v0.1.12.post1 (with 5759ee2):
  if (capturing) {
      graph_unreg_input_buffers_.push_back(input);   // always push
  } else { /* cache lookup */ }

  // v0.1.12 / v0.1.11.post1 (without 5759ee2):
  auto it = input_buffer.find(input);
  if (it != input_buffer.end()) { ptrs = it->second; }   // cache hit short-circuits
  else if (capturing) { graph_unreg_input_buffers_.push_back(input); ... }
  ```

  Intent was correctness (keep `graph_unreg_*` length consistent across ranks when allocators reuse different addresses). Suspected side effect: with many captured graphs (Qwen3-235B × sglang captures across many batch sizes × layers × fused-AR ops), `graph_unreg_*`
  grows unboundedly. `flush_graph_buffers` at capture exit then does thousands of `hipIpcGetMemHandle` / `hipIpcOpenMemHandle` / `hipMemcpy(H2D)` calls in the still-capturing window, plausibly racing with the NCCL watchdog → `hipErrorStreamCaptureUnsupported`.

  Lines up with the observations:
  - v0.1.11.post1 passes: cache hits dominate after iter 0, danger window stays empty.
  - DeepSeek-R1 / GLM5 pass: fewer captured graphs → small `graph_unreg_*`.
  - gloo→TCPStore is a minor timing amplifier, not the driver.

  ## Suggested next step

  `5759ee2` only exists in **v0.1.12.post1**. The plain **v0.1.12** tag does not contain it, and main has reverted it via [`d098ae5`](https://github.com/ROCm/aiter/commit/d098ae5) ("Revert 'fix(car): craph capture err' (#2735)").

  Could you try bumping `AITER_COMMIT_DEFAULT` from `v0.1.12.post1` to `v0.1.12` (or a recent main past `d098ae5`) and report back? If the crash is gone, that confirms `5759ee2` is the trigger. If not, we'll need to dig further.

  > The original correctness issue `5759ee2` was trying to fix (cross-rank `graph_unreg_*` divergence) is still open — proper solution (e.g. idempotent/dedup'd push) TBD.

**Comment by bingxche** [comment]
Thanks for your reply, the job still failed at commit `e3225be47c82fd756ea8773cfe9f4666ab131573` (on 20 Apr, past `d098ae5` )
https://github.com/sgl-project/sglang/actions/runs/24688191049/job/72202954564

<img width="2103" height="1519" alt="Image" src="https://github.com/user-attachments/assets/c38d17de-9159-4feb-9935-68b97d4172dc" />

**Comment by Jacob0226** [comment]
hi @TennyWang1223 , I was working on testing this issue with different approaches. FYI

Problem: HIP runtime bug on ROCm ≤ 7.2.0 — cross-thread `hipEventQuery` ignores THREAD_LOCAL capture mode, so the NCCL watchdog invalidates graph captures on another thread (pytorch/pytorch#177309). aiter v0.1.12.post1's IPCBufferPool change only widened the race window; the bug itself was already there. 

Option 1: Bump `BASE_IMAGE_*_ROCM720` to `rocm/pytorch:rocm7.2.2_ubuntu22.04_
py3.10_pytorch_release_2.9.1`. ROCm 7.2.2 has the runtime fix; zero C++ rebuild.

Option 2: Keep ROCm 7.2.0 base, upgrade torch to include PR #176251 (merged to main 2026-03-17). userspace workaround; no base-image change.

I will tested these solutions and keep you all posted. cc @bingxche

**Comment by Jacob0226** [comment]
Hi @TennyWang1223 @bingxche,

Root cause:
The issue has been traced to a bug in ROCm 7.2.0, as reported in the PyTorch community (https://github.com/pytorch/pytorch/pull/176251
).
Specifically, hipEventQuery breaks HIP graph execution when SGLang performs capture batch. This bug has been confirmed by the ROCm team and was fixed in ROCm 7.2.1 and later. Although a fix was proposed in PyTorch, the PR was reverted after ROCm 7.2.1 was released.

Resolution:
The only viable solution is to upgrade ROCm to 7.2.1 or later.

Current status:
After upgrading to ROCm 7.2.2, the GSM8K accuracy dropped to 0.90, below the threshold of 0.93. This appears to be a separate issue related to fused_moe.py and will require further investigation.

@bingxche I believe this original issue can be closed, as the root cause has been identified and addressed via the ROCm upgrade.
